<?php

$tz_date_slider    =   array(
    1     =>  1,
    2     =>  2,
    3     =>  3,
    4     =>  4,
    5     =>  5,
    6     =>  6,
    7     =>  7,
    8     =>  8,
    9     =>  9,
    10    =>  10,
    11    =>  11,
    12    =>  12,
    13    =>  13,
    14    =>  14,
    15    =>  15,
    16    =>  16,
    17    =>  17,
    18    =>  18,
    19    =>  19,
    20    =>  20,
    21    =>  21,
    22    =>  22,
    23    =>  23,
    24    =>  24,
    25    =>  25,
    26    =>  26,
    27    =>  27,
    28    =>  28,
    29    =>  29,
    30    =>  30,
    31    =>  31
);
$tz_month_slider   =   array(
    esc_html__("January", "tz-plazart")    =>  1,
    esc_html__("February", "tz-plazart")   =>  2,
    esc_html__("March", "tz-plazart")      =>  3,
    esc_html__("April", "tz-plazart")      =>  4,
    esc_html__("May", "tz-plazart")        =>  5,
    esc_html__("June", "tz-plazart")       =>  6,
    esc_html__("July", "tz-plazart")       =>  7,
    esc_html__("August", "tz-plazart")     =>  8,
    esc_html__("September", "tz-plazart")  =>  9,
    esc_html__("October", "tz-plazart")    =>  10,
    esc_html__("November", "tz-plazart")   =>  11,
    esc_html__("December", "tz-plazart")   =>  12,
);

/* Start tz_slider_home_meetup */
vc_map( array(
    "name"              =>  "Home Slider",
    "base"              =>  "tz_slider_home_meetup",
    "weight"            =>  1,
    "category"          =>  'Maniva Meetup',
    "icon"              =>  "icon-element",
    "params"            =>  array(
        array(
            "type"          => "dropdown",
            "class"         => "",
            "heading"       => esc_html__("Type Slider", "tz-plazart"),
            "param_name"    => "type_slider",
            "description"   => esc_html__("Type of transition between slides", "tz-plazart"),
            "value"         => array(
                esc_html__("Slider images", "tz-plazart")      =>  'slider_img',
                esc_html__("Video background", "tz-plazart")   =>  'video_bk',
            ),
            "group"         => esc_html__("Slider Home","tz-plazart"),
        ),
        array(
            "type"          => "dropdown",
            "class"         => "",
            "heading"       => esc_html__("Overlay Slider", "tz-plazart"),
            "param_name"    => "type_overlay_slider",
            "description"   => esc_html__("Type of transition between slides", "tz-plazart"),
            "value"         => array(
                esc_html__("Show", "tz-plazart")   =>  1,
                esc_html__("Hide", "tz-plazart")   =>  0,
            ),
            "group"         => esc_html__("Slider Home","tz-plazart"),
        ),
        array(
            "type"          =>  "colorpicker",
            "class"         =>  "",
            "heading"       =>  esc_html__("Color Overlay Slider", "tz-plazart"),
            "param_name"    =>  "color_overlay_slider",
            "value"         =>  "",
            "dependency"    => Array('element' => "type_overlay_slider", 'value' => '1'),
            "group"         => esc_html__("Slider Home","tz-plazart"),
        ),
        array(
            "type"          =>  "attach_images",
            "heading"       => esc_html__("Upload images slider", "tz-plazart"),
            "param_name"    =>  "image_slider",
            "value"         =>  "",
            "dependency"    =>  Array('element' => "type_slider", 'value' => array('slider_img')),
            "group"         => esc_html__("Slider Home","tz-plazart"),
        ),
        array(
            "type"          => "dropdown",
            "class"         => "",
            "heading"       => esc_html__("Auto Slider", "tz-plazart"),
            "param_name"    => "auto_slider",
            "description"   => esc_html__("Slides will automatically transition", "tz-plazart"),
            "value"         => array(
                esc_html__("Yes", "tz-plazart")    =>    1,
                esc_html__("No", "tz-plazart")     =>    0,
            ),
            "dependency"    =>  Array('element' => "type_slider", 'value' => array('slider_img')),
            "group"         => esc_html__("Slider Home","tz-plazart"),
        ),
        array(
            "type"          =>  "textfield",
            "class"         =>  "",
            "heading"       =>  esc_html__("Speed Next Slide Automatically", "tz-plazart"),
            "param_name"    =>  "speed",
            "value"         =>  6000,
            "description"   => esc_html__("Slide transition duration (in ms)", "tz-plazart"),
            "dependency"    =>  Array('element' => "auto_slider", 'value' => array('1')),
            "group"         => esc_html__("Slider Home","tz-plazart"),
        ),
        array(
            "type"          =>  "textfield",
            "class"         =>  "",
            "heading"       =>  esc_html__("Speed Slider", "tz-plazart"),
            "param_name"    =>  "speed_slider",
            "value"         =>  1000,
            "description"   => esc_html__("Slide transition duration (in ms)", "tz-plazart"),
            "dependency"    =>  Array('element' => "type_slider", 'value' => array('slider_img')),
            "group"         => esc_html__("Slider Home","tz-plazart"),
        ),
        array(
            "type"          => "dropdown",
            "class"         => "",
            "heading"       => esc_html__("Type modem slider", "tz-plazart"),
            "param_name"    => "modem",
            "description"   => esc_html__("Type of transition between slides", "tz-plazart"),
            "value"         => array(
                esc_html__("Fade", "tz-plazart")   =>  'fade',
                esc_html__("Slide", "tz-plazart")  =>  'slide',
            ),
            "dependency"    =>  Array('element' => "type_slider", 'value' => array('slider_img')),
            "group"         => esc_html__("Slider Home","tz-plazart"),
        ),
        array(
            "type"          => "dropdown",
            "class"         => "",
            "heading"       => esc_html__("Slider navigation", "tz-plazart"),
            "param_name"    => "slider_navigation",
            "value"         => array(
                esc_html__("Show", "tz-plazart")   =>  1,
                esc_html__("Hide", "tz-plazart")   =>  0,
            ),
            "dependency"    =>  Array('element' => "type_slider", 'value' => array('slider_img')),
            "group"         => esc_html__("Slider Home","tz-plazart"),
        ),
        array(
            "type"          => "dropdown",
            "class"         => "",
            "heading"       => esc_html__("Slides pagination", "tz-plazart"),
            "param_name"    => "slides_pagination",
            "value"         => array(
                esc_html__("Show", "tz-plazart")   =>  1,
                esc_html__("Hide", "tz-plazart")   =>  0,
            ),
            "dependency"    =>  Array('element' => "type_slider", 'value' => array('slider_img')),
            "group"         => esc_html__("Slider Home","tz-plazart"),
        ),
        array(
            'type'          =>  "textfield",
            'heading'       =>  esc_html__("Video mp4 url eg: .mp4", "tz-plazart"),
            'param_name'    =>  "video_mp4",
            "value"         =>  "",
            "dependency"    =>  Array('element' => "type_slider", 'value' => array('video_bk')),
            "group"         => esc_html__("Slider Home","tz-plazart"),
        ),
        array(
            'type'          =>  "textfield",
            'heading'       =>  esc_html__("Video ogv url eg: .ogv", "tz-plazart"),
            'param_name'    =>  "video_ogg",
            "value"         =>  "",
            "dependency"    =>  Array('element' => "type_slider", 'value' => array('video_bk')),
            "group"         => esc_html__("Slider Home","tz-plazart"),
        ),
        array(
            'type'          =>  "textfield",
            'heading'       =>  esc_html__("Video web url eg: .webm", "tz-plazart"),
            'param_name'    =>  "video_web",
            "value"         =>  "",
            "dependency"    =>  Array('element' => "type_slider", 'value' => array('video_bk')),
            "group"         => esc_html__("Slider Home","tz-plazart"),
        ),
        array(
            "type"          => "checkbox",
            "class"         => "",
            "heading"       => "",
            "param_name"    => "open_link",
            "value"         => array(
                'Open link in a new window/tab'      => 'link_target',
            ),
            "group"         =>  esc_html__("Social Network","tz-plazart"),
        ),
        array(
            "type"          => "textfield",
            "class"         => "",
            "heading"       => esc_html__("Facebook Url", "tz-plazart"),
            "param_name"    => "facebook_url",
            "value"         => "",
            "group"         =>  esc_html__("Social Network","tz-plazart"),
        ),
        array(
            "type"          => "textfield",
            "class"         => "",
            "heading"       => esc_html__("twitter Url", "tz-plazart"),
            "description"   => "",
            "param_name"    => "twitter_url",
            "value"         => "",
            "group"         =>  esc_html__("Social Network","tz-plazart"),
        ),
        array(
            "type"          => "textfield",
            "class"         => "",
            "heading"       => esc_html__("Flickr Url", "tz-plazart"),
            "description"   => "",
            "param_name"    => "flickr_url",
            "value"         => "",
            "group"         =>  esc_html__("Social Network","tz-plazart"),
        ),
        array(
            "type"          => "textfield",
            "class"         => "",
            "heading"       => esc_html__("GooglePlus Url", "tz-plazart"),
            "description"   => "",
            "param_name"    => "googleplus_url",
            "value"         => "",
            "group"         =>  esc_html__("Social Network","tz-plazart"),
        ),
        array(
            "type"          => "textfield",
            "class"         => "",
            "heading"       => esc_html__("Instagram Url", "tz-plazart"),
            "description"   => "",
            "param_name"    => "instagram_url",
            "value"         => "",
            "group"         =>  esc_html__("Social Network","tz-plazart"),
        ),
        array(
            "type"          => "textarea_html",
            "heading"       => "Content",
            "param_name"    => "content",
            "value"         => "",
            "group"         =>  esc_html__("Text Box", "tz-plazart"),
        ),
        array(
            "type"          => "dropdown",
            "class"         => "",
            "heading"       => esc_html__("Click Button One Page", "tz-plazart"),
            "param_name"    => "btn_one_page",
            "value"         => array(
                esc_html__("Yes", "tz-plazart")    =>    1,
                esc_html__("No", "tz-plazart")     =>    0,
            ),
            "group"         =>  esc_html__("Text Box", "tz-plazart"),
        ),
        array(
            "type"          => "textfield",
            "class"         => "",
            "heading"       => esc_html__("Text Button 1", "tz-plazart"),
            "param_name"    => "text_btn_1",
            "value"         => "",
            "group"         =>  esc_html__("Text Box", "tz-plazart"),
        ),
        array(
            "type"          => "textfield",
            "class"         => "",
            "heading"       => esc_html__("Link Button 1", "tz-plazart"),
            "param_name"    => "link_btn_1",
            "value"         => "",
            "group"         =>  esc_html__("Text Box", "tz-plazart"),
        ),
        array(
            "type"          => "textfield",
            "class"         => "",
            "heading"       => esc_html__("Text Button 2", "tz-plazart"),
            "param_name"    => "text_btn_2",
            "value"         => "",
            "group"         =>  esc_html__("Text Box", "tz-plazart"),
        ),
        array(
            "type"          => "textfield",
            "class"         => "",
            "heading"       => esc_html__("Link Button 2", "tz-plazart"),
            "param_name"    => "link_btn_2",
            "value"         => "",
            "group"         =>  esc_html__("Text Box", "tz-plazart"),
        ),
        array(
            "type"          => "dropdown",
            "class"         => "",
            "heading"       => esc_html__("Shape", "tz-plazart"),
            "param_name"    => "shape_btn",
            "value"         => array(
                esc_html__("Round", "tz-plazart")      =>  1,
                esc_html__("Square", "tz-plazart")     =>  2,
                esc_html__("Rounded", "tz-plazart")    =>  3,
            ),
            "group"         =>  esc_html__("Text Box", "tz-plazart"),
        ),
        array(
            "type"          => "dropdown",
            "class"         => "",
            "heading"       => esc_html__("Show hide Count Down", "tz-plazart"),
            "param_name"    => "hide_count_down",
            "value"         => array(
                esc_html__("Show", "tz-plazart")   =>  'show',
                esc_html__("Hide", "tz-plazart")   =>  'hide',
            ),
            'group'         => esc_html__( 'Count Down', 'tz-plazart' ),
        ),
        array(
            "type"          =>  "dropdown",
            "class"         =>  "",
            "heading"       =>  esc_html__("Date", "tz-plazart"),
            "param_name"    =>  "date",
            "value"         => $tz_date_slider,
            'group'         => esc_html__( 'Count Down', 'tz-plazart' ),
        ),
        array(
            "type"          =>  "dropdown",
            "class"         =>  "",
            "heading"       =>  esc_html__("Month", "tz-plazart"),
            "param_name"    =>  "month",
            "value"         => $tz_month_slider,
            "group"         =>  esc_html__("Count Down","tz-plazart"),
        ),
        array(
            "type"          =>  "textfield",
            "class"         =>  "",
            "heading"       =>  esc_html__("Year", "tz-plazart"),
            "description"   =>  "import year by number eg: 2016",
            "param_name"    =>  "year",
            "value"         =>  2016,
            "group"         =>  esc_html__("Count Down","tz-plazart"),
        ),
        array(
            "type"          =>  "textfield",
            "class"         =>  "",
            "heading"       =>  esc_html__("Time", "tz-plazart"),
            "description"   =>  "Import time eg: 23:59:59",
            "param_name"    =>  "time",
            "value"         =>  '23:59:59',
            "group"         =>  esc_html__("Count Down","tz-plazart"),
        ),
        array(
            "type"          => "textfield",
            "class"         => "",
            "heading"       => esc_html__("Text Days", "tz-plazart"),
            "param_name"    => "text_day",
            "value"         => "days",
            "group"         =>  esc_html__("Count Down","tz-plazart"),
        ),
        array(
            "type"          => "textfield",
            "class"         => "",
            "heading"       => esc_html__("Text Hours", "tz-plazart"),
            "param_name"    => "text_hour",
            "value"         => "hours",
            "group"         =>  esc_html__("Count Down","tz-plazart"),
        ),
        array(
            "type"          => "textfield",
            "class"         => "",
            "heading"       => esc_html__("Text Mins", "tz-plazart"),
            "param_name"    => "text_min",
            "value"         => "mins",
            "group"         =>  esc_html__("Count Down","tz-plazart"),
        ),
        array(
            "type"          => "textfield",
            "class"         => "",
            "heading"       => esc_html__("Text Secs", "tz-plazart"),
            "param_name"    => "text_sec",
            "value"         => "secs",
            "group"         =>  esc_html__("Count Down","tz-plazart"),
        ),
        array(
            "type"          => "dropdown",
            "class"         => "",
            "heading"       => esc_html__("Show hide Event ended", "tz-plazart"),
            "param_name"    => "hide_event_ended",
            "value"         => array(
                esc_html__("Show", "tz-plazart")   =>  'show',
                esc_html__("Hide", "tz-plazart")   =>  'hide',
            ),
            'group'         => esc_html__( 'Count Down', 'tz-plazart' ),
        ),
        array(
            "type"          =>  "textfield",
            "class"         =>  "",
            "heading"       =>  esc_html__("Event ended", "tz-plazart"),
            "param_name"    =>  "event_ended",
            "value"         =>  'The event is ended',
            "dependency"    => array('element' => 'hide_event_ended', 'value' => array('show')),
            "group"         =>  esc_html__("Count Down","tz-plazart"),
        ),
    )
) );
/* End tz_slider_home_meetup */