<?php

vc_map( array(
    "name"          =>  esc_html__("Our Speakers", "tz-plazart"),
    "base"          =>  "tz_our_speakers",
    "icon"          =>  "icon-element",
    "description"   =>  "",
    "class"         =>  "tzElement_extended",
    "category"      =>  esc_html__("Maniva Meetup", "tz-plazart"),
    "params"        =>  array(
        array(
            "type"          => "attach_image",
            "heading"       => esc_html__("Image Speakers", "tz-plazart"),
            "param_name"    => "speakers_image",
            "description"   => esc_html__("Upload image of member in team.", "tz-plazart"),
            "group"         => esc_html__("Speakers","tz-plazart"),
        ),
        array(
            "type"          => "textfield",
            "class"         => "",
            "heading"       => "Name",
            "param_name"    => "name",
            "group"         =>  esc_html__("Speakers","tz-plazart"),
        ),
        array(
            "type"          => "textfield",
            "class"         => "",
            "heading"       => "Employment",
            "param_name"    => "employment",
            "group"         =>  esc_html__("Speakers","tz-plazart"),
        ),
        array(
            "type"          => "textarea_html",
            "heading"       => "Content",
            "param_name"    => "content",
            "value"         => "",
            "description"   =>  "Show on click light box",
            "group"         =>  esc_html__("Speakers","tz-plazart"),
        ),
        array(
            "type"          => "checkbox",
            "class"         => "",
            "heading"       => "",
            "param_name"    => "use_excerpt",
            "value"         => array(
                'Use Excerpt'      => 1,
            ),
            "group"         =>  esc_html__("Speakers","tz-plazart"),
        ),
        array(
            "type"          => "textarea",
            "class"         => "",
            "heading"       => esc_html__("Excerpt", "tz-plazart"),
            "param_name"    => "excerpt_speakers",
            "value"         => "",
            "dependency"    => Array('element' => "use_excerpt", 'value' => array('1')),
            "description"   => "Excerpts are optional hand-crafted summaries of your content that can be used in your theme",
            "group"         =>  esc_html__("Speakers","tz-plazart"),
        ),
        array(
            "type"          =>  "colorpicker",
            "class"         => "",
            "heading"       => "Color Excerpt",
            "param_name"    => "color_excerpt",
            "value"         =>  "",
            "dependency"    => Array('element' => "use_excerpt", 'value' => array('1')),
            "group"         =>  esc_html__("Speakers","tz-plazart"),
        ),
        array(
            "type"          => "checkbox",
            "class"         => "",
            "heading"       => "",
            "param_name"    => "open_link",
            "value"         => array(
                'Open link in a new window/tab'      => 'link_target',
            ),
            "group"         =>  esc_html__("Social Network","tz-plazart"),
        ),
        array(
            "type"          => "textfield",
            "class"         => "",
            "heading"       => esc_html__("Facebook Url", "tz-plazart"),
            "param_name"    => "facebook_url",
            "value"         => "",
            "group"         =>  esc_html__("Social Network","tz-plazart"),
        ),
        array(
            "type"          => "textfield",
            "class"         => "",
            "heading"       => esc_html__("twitter Url", "tz-plazart"),
            "description"   => "",
            "param_name"    => "twitter_url",
            "value"         => "",
            "group"         =>  esc_html__("Social Network","tz-plazart"),
        ),
        array(
            "type"          => "textfield",
            "class"         => "",
            "heading"       => esc_html__("Flickr Url", "tz-plazart"),
            "description"   => "",
            "param_name"    => "flickr_url",
            "value"         => "",
            "group"         =>  esc_html__("Social Network","tz-plazart"),
        ),
        array(
            "type"          => "textfield",
            "class"         => "",
            "heading"       => esc_html__("GooglePlus Url", "tz-plazart"),
            "description"   => "",
            "param_name"    => "googleplus_url",
            "value"         => "",
            "group"         =>  esc_html__("Social Network","tz-plazart"),
        ),
        array(
            "type"          => "textfield",
            "class"         => "",
            "heading"       => esc_html__("Instagram Url", "tz-plazart"),
            "description"   => "",
            "param_name"    => "instagram_url",
            "value"         => "",
            "group"         =>  esc_html__("Social Network","tz-plazart"),
        ),
        array(
            "type"          => "textfield",
            "class"         => "",
            "heading"       => esc_html__("Linkedln Url", "tz-plazart"),
            "description"   => "",
            "param_name"    => "linkedln_url",
            "value"         => "",
            "group"         =>  esc_html__("Social Network","tz-plazart"),
        ),
        array(
            "type"          =>  "dropdown",
            "heading"       =>  esc_html__("Use Effects Light Box", "tz-plazart"),
            "param_name"    =>  "use_effects",
            "value"         => array(
                "Yes"   =>  1,
                "No"    =>  0,
            ),
            "group"         =>  esc_html__("Effects Light Box","tz-plazart"),
        ),
        array(
            "type"          => "attach_image",
            "heading"       => esc_html__("Image Speakers Square", "tz-plazart"),
            "param_name"    => "speakers_image_square",
            "description"   => esc_html__("Upload an square image. This image will be shown in lightbox.  In case, this image is not uploaded, the image in Speaker tab will be used.", "tz-plazart"),
            "group"         =>  esc_html__("Effects Light Box","tz-plazart"),
        ),
        array(
            "type"          =>  "dropdown",
            "heading"       =>  esc_html__("Style Effects Light Box", "tz-plazart"),
            "param_name"    =>  "effects_light_box",
            "description"   =>  '<a href="http://tympanus.net/Development/ModalWindowEffects/" target="_blank">Demo Effects Light Box</a>',
            "value"         => array(
                "Fade In &amp; Scale"   =>  1,
                "Slide in (right)"      =>  2,
                "Slide in (bottom)"     =>  3,
                "Newspaper"             =>  4,
                "Fall"                  =>  5,
                "Side Fall"             =>  6,
                "Sticky Up"             =>  7,
                "3D Flip (horizontal)"  =>  8,
                "3D Flip (vertical)"    =>  9,
                "3D Sign"               =>  10,
                "Super Scaled"          =>  11,
                "Just Me"               =>  12,
                "3D Slit"               =>  13,
                "3D Rotate Bottom"      =>  14,
                "3D Rotate In Left"     =>  15,
                "Blur"                  =>  16,
                "Let me in"             =>  17,
                "Make way!"             =>  18,
                "Slip from top"         =>  19
            ),
            "group"         =>  esc_html__("Effects Light Box","tz-plazart"),
        ),
        array(
            "type"          => "textfield",
            "class"         => "",
            "heading"       => esc_html__("Text", "tz-plazart"),
            "description"   => "",
            "param_name"    => "text_thank",
            "value"         => "Thanks for watching!",
            "group"         =>  esc_html__("Effects Light Box","tz-plazart"),
        ),
        array(
            "type"          =>  "colorpicker",
            "class"         => "",
            "heading"       => "Color Text",
            "param_name"    => "color_text_thank",
            "value"         =>  "",
            "group"         =>  esc_html__("Effects Light Box","tz-plazart"),
        ),
        array(
            "type"          =>  "colorpicker",
            "class"         => "",
            "heading"       => "Color Text Name",
            "param_name"    => "color_text_name",
            "description"   => "Text Name Effects Light Box",
            "value"         =>  "",
            "group"         =>  esc_html__("Effects Light Box","tz-plazart"),
        ),
        array(
            "type"          =>  "colorpicker",
            "class"         => "",
            "heading"       => "Color Text Employment",
            "param_name"    => "color_text_employment",
            "description"   => "Text Employment Effects Light Box",
            "value"         =>  "",
            "group"         =>  esc_html__("Effects Light Box","tz-plazart"),
        ),
        array(
            "type"          =>  "dropdown",
            "heading"       =>  esc_html__("Type hover", "tz-plazart"),
            "param_name"    =>  "type_hover",
            "value"         => array(
                "Hover Show Social Network" =>  1,
                "Hover Show Text"           =>  2,
            ),
            "group"         =>  esc_html__("Speaker Hover","tz-plazart"),
        ),
        array(
            "type"          => "textfield",
            "class"         => "",
            "heading"       => esc_html__("Text", "tz-plazart"),
            "description"   => "",
            "param_name"    => "text_hover",
            "value"         => "view profile",
            "group"         =>  esc_html__("Speaker Hover","tz-plazart"),
            "dependency"    => Array('element' => "type_hover", 'value' => array('2')),
        ),
        array(
            "type"          =>  "colorpicker",
            "class"         => "",
            "heading"       => "Color Text",
            "param_name"    => "color_text_hover",
            "value"         =>  "",
            "group"         =>  esc_html__("Speaker Hover","tz-plazart"),
            "dependency"    => Array('element' => "type_hover", 'value' => array('2')),
        ),
        array(
            "type"          =>  "colorpicker",
            "class"         => "",
            "heading"       => "Background Text",
            "param_name"    => "bk_text_hover",
            "value"         =>  "",
            "group"         =>  esc_html__("Speaker Hover","tz-plazart"),
            "dependency"    => Array('element' => "type_hover", 'value' => array('2')),
        ),
    )
) );