<?php

vc_map( array(
    "name" => esc_html__("Skill Graphics", "tz-plazart"),
    "icon" => "icon-element",
    "weight" => 1,
    "base" => "tz-skill-item",
    "class" => "tzElement_extended",
    "description" => "",
    "category" => esc_html__("Maniva Meetup", "tz-plazart"),
    "params" => array(
        array(
            "type"          => "dropdown",
            "heading"       => esc_html__("Skill Graphics Style", "tz-plazart"),
            "param_name"    => "style_skill",
            "admin_label"   => true,
            "value"         => array(
                esc_html__("Type 1", "tz-plazart") => 1,
                esc_html__("Type 2", "tz-plazart") => 2,
                esc_html__("Type 3", "tz-plazart") => 3,
                esc_html__("Type 4", "tz-plazart") => 4,),
            "group"         => esc_html__("Skill Graphics","tz-plazart"),
        ),
        array(
            "type"          => "textfield",
            "class"         => "",
            "admin_label"   => true,
            "heading"       => esc_html__("Title", "tz-plazart"),
            "param_name"    => "title",
            "value"         =>  "Marketing",
            "group"         => esc_html__("Skill Graphics","tz-plazart"),
        ),
        array(
            "type"          => "textfield",
            "class"         => "",
            "admin_label"   => true,
            "heading"       => esc_html__("Value", "tz-plazart"),
            "param_name"    => "value_graphics",
            "value"         =>  "70",
            "description"   => "Enter Value of Skill Graphics.",
            "group"         => esc_html__("Skill Graphics","tz-plazart"),
        ),
        array(
            "type"          => "textfield",
            "class"         => "",
            "admin_label"   => true,
            "heading"       => esc_html__("Units", "tz-plazart"),
            "param_name"    => "units_graphics",
            "value"         =>  "",
            "description"   => "Enter measurement units (Example: %, px, points, etc. Note: graph value and units will be appended to graph title).",
            "group"         => esc_html__("Skill Graphics","tz-plazart"),
        ),
        array(
            "type"          =>  "colorpicker",
            "class"         =>  "",
            "heading"       =>  esc_html__("Color Title", "tz-plazart"),
            "param_name"    =>  "color_title",
            "value"         =>  "",
            "group"         => esc_html__("Setting Skill Graphics","tz-plazart"),
        ),
        array(
            "type"          =>  "colorpicker",
            "class"         =>  "",
            "heading"       =>  esc_html__("Color Value", "tz-plazart"),
            "param_name"    =>  "color_value",
            "value"         =>  "",
            "group"         => esc_html__("Setting Skill Graphics","tz-plazart"),
        ),
        array(
            "type"          =>  "colorpicker",
            "class"         =>  "",
            "admin_label"   => true,
            "heading"       =>  esc_html__("Background Color Graphics", "tz-plazart"),
            "param_name"    =>  "bk_graphics",
            "value"         =>  "",
            "group"         => esc_html__("Setting Skill Graphics","tz-plazart"),
        ),
        array(
            "type"          =>  "colorpicker",
            "class"         =>  "",
            "admin_label"   => true,
            "heading"       =>  esc_html__("Background Color Bar", "tz-plazart"),
            "param_name"    =>  "bk_bar",
            "value"         =>  "",
            "group"         => esc_html__("Setting Skill Graphics","tz-plazart"),
        ),
    )
) );